blank_issues_enabled: true
contact_links:
  - name: Create new issue
    url: https://new-issue.antv.vision/
    about: The issue which is not created via https://new-issue.antv.vision/ will be closed immediately.
